### ISSUE TITLE
Timeline is not included in Mission Post Emails

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#10]
Emails should including the Timeline, but that field is blank in all functionality. This does work with the chronological_mission_posts mod.

ordered_mission_posts email
A Mission Post by Captain Test Testerman
Mission: Test Mission
Location: test
Timeline:

chronological_mission_posts email
A Mission Post by Captain Test Testerman
Mission: Test Mission
Location: test
Timeline: Mission Day 1 at 1030

**Comment by reecesavage** [comment]
Adding the Parser helper does add the Timeline information to the email, but not in the expected format.

Stardate Current:
Timeline: Mission Day 123456.79 at 123456.79
Stardate Correct:
Timeline: Stardate 123456.79 at 0830

Mission Day Time Current:
Timeline: Mission Day 1 at 1
Mission Day Time Correct:
Timeline: Mission Day 1 at 0830

Mission Date Time Current:
Timeline: Mission Day 1 at 1
Mission Date Time Correct:
Timeline: Date 2399/11/31 at 0830

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
tested fixed
