### ISSUE TITLE
Add Post Numbers to Mission Post Title in Email

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#12]
If Post Numbers is enabled for a Mission then prepend the Post Number to the Mission Post Title when emailing the Mission Post.

**Comment by pawanmall157** [comment]
i guess we need to save post number for now what we are doing is calculating number of rows according to sort order.

Suppose we have added 10 post in one mission so the added post should be post number=11 right

**Comment by reecesavage** [comment]
Could we run the calculation at post time as the email is built?

**Comment by pawanmall157** [comment]
Yes we can but both the post number can be different at that case 
1->At email time 
2->At mission post list 

Why these can be different
At email build we are calculating from existing mission post but at list view we are calculating according to sort attribute

**Comment by reecesavage** [comment]
If Post Numbering is enabled for the mission then the sort should always be Nova Default.
post_status = activated and post_date in the posts table.

**Comment by reecesavage** [comment]
The Title is part of the Email Subject.

![2021-02-03 09_33_30-Window](https://user-images.githubusercontent.com/15860882/106770072-3a101680-6603-11eb-833e-39e615652a37.png)

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
tested fixed
