### ISSUE TITLE
Update Mission Date and Mission Default Date Fields to use Nova Default Styling.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#17]
Update the date picker and field for Mission Date and Default Mission Date to look like base date fields in Nova.

You can get the classes off the Start Date and End Date fields.

![image](https://user-images.githubusercontent.com/15860882/106949272-5939a180-66f2-11eb-9039-f6810176b14c.png)

**Comment by pawanmall157** [comment]
![Capture](https://user-images.githubusercontent.com/63999236/107044258-0e02ba00-67ea-11eb-8d31-0e86b7c8d588.PNG)
So you want this datepicker ?

**Comment by reecesavage** [comment]
Correct, and the field data is formatted correctly as well.

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
![image](https://user-images.githubusercontent.com/15860882/107547915-a5259400-6b93-11eb-86e7-e72630190d26.png)
Default Mission Date Label is missing

**Comment by pawanmall157** [comment]
![Capture](https://user-images.githubusercontent.com/63999236/107859990-05058e80-6e63-11eb-8e0c-ff70b04e24a0.PNG)

Default mission date label is blank in admin section

**Comment by reecesavage** [comment]
Adding the label doesn't stick when clicking submit. 
![image](https://user-images.githubusercontent.com/15860882/107860193-96ddaf00-6e03-11eb-9a42-93fc6f37c665.png)

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed fixed
