### ISSUE TITLE
Only allow legacy mode day time if enabled in the admin panel.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#18]
Only provide the Legacy Mode checkbox if Legacy Mode is enabled in the admin control panel and if the mission id is in the list of created missions. Should only show as an option in manage/missions/edit and only for missions that existed when the option was enabled in the admin control panel.

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed fixed
