### ISSUE TITLE
add sql indexes

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#19]
Add SQL index for faster queries. The admin page should check for the presence of the index. The index should be created only if all of the columns exist.

```CREATE INDEX post_ordered_mission_post ON nova_posts (`nova_ext_ordered_post_day`,`nova_ext_ordered_post_date`,`nova_ext_ordered_post_stardate`,`nova_ext_ordered_post_time`);```

**Comment by pawanmall157** [comment]
added

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
index is created
