### ISSUE TITLE
Legacy Mode Day and Time not sticking and not emailed

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#21]
When legacy mode is enabled the day and time aren't sticking if you save a post.

Also, Mission Day and Time aren't parsed in the email.

![2021-02-16 16_19_24-USS Test __ Write Mission Post](https://user-images.githubusercontent.com/15860882/108128949-1e7d2500-7073-11eb-8fb4-e16d3d7a1cde.png)
![2021-02-16 16_19_37- USS Test  Test Mission - test (Saved Mission Post) - reece savage@gmail com - G](https://user-images.githubusercontent.com/15860882/108128950-1f15bb80-7073-11eb-9dcb-c1f410333190.png)

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed fixed
