### ISSUE TITLE
Timeline is not visible on the posts

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#22]
When viewing a post the Timeline is not visible. 

![2021-02-16 16_24_14-USS Test __ Test Mission - test](https://user-images.githubusercontent.com/15860882/108129327-a8c58900-7073-11eb-878c-e55b6c0f1f2e.png)

https://novadev.game-hosting.org/index.php/sim/viewpost/32

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
There is also a view off of the Write controller. It also needs to show the timeline.

![image](https://user-images.githubusercontent.com/15860882/108247933-e5978b80-7118-11eb-9915-55bd2dba3fbb.png)

You can get to that view from our saved post.
https://novadev.game-hosting.org/index.php/write/missionpost/33/view

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed fixed
