### ISSUE TITLE
Posts aren't sorted correctly when Timeline Configuration set to Nova Default

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#24]
![image](https://user-images.githubusercontent.com/15860882/108608072-09153d00-738a-11eb-8552-9cbe0b7f96f0.png)

When the Timeline Configuration is set to Nova Default and Post Numbering is not enabled the post sort order is incorrect. 

The post titled Test Order should be at the bottom of the list.

Posts should be ordered by the post_date column and post_status is "activated".

**Comment by pawanmall157** [comment]
fixed
