### ISSUE TITLE
Feature Request: Adapting Navigation Buttons

### ISSUE THREAD

**Issue by greenfelt22** [reecesavage/nova-ext-ordered-mission-posts#26]
When reading published posts sorted by this extension, the arrow keys still follow the original published order. Can these be overridden by the way the posts are organized by the extension?

![image](https://user-images.githubusercontent.com/25126048/111399783-10cbb700-8694-11eb-808a-f03b2d38eca5.png)

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
@greenfelt22 would you mind pulling down the main branch to check the functionality?

**Comment by greenfelt22** [comment]
Works perfectly! Thanks!

**Comment by reecesavage** [comment]
Thanks, @greenfelt22 
Fixed in v1.0.4
