### ISSUE TITLE
Incompatibility with custom table names

### ISSUE THREAD

**Issue by greenfelt22** [reecesavage/nova-ext-ordered-mission-posts#30]
This extension for Nova doesn't take into account databases that may have a custom prefix for their database tables. 

![image](https://user-images.githubusercontent.com/25126048/120109069-7674fe80-c12d-11eb-83eb-cdbe4a38018b.png)

I have been able to manually add the necessary fields, but the extension continues to look for `nova_posts` et al, instead of `{customprefix}_posts` et al. I could edit the extension to allow for my own custom table prefixes but I would have to continuously do this every time I need to update the extension.

**Comment by reecesavage** [comment]
Fixed in v1.1.1 @greenfelt22
