### ISSUE TITLE
Word Count brings up the delete box when in any other state than current mission.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#35]
Word Count brings up the delete box instead of the word count box when a mission is not in a state of current mission. Occurs for Upcoming Missions and Completed Missions.

![image](https://user-images.githubusercontent.com/15860882/150893062-2581b747-08d4-4dec-88d1-a5cf822630a2.png)

**Comment by pawanmall157** [comment]
Fixed

**Comment by reecesavage** [comment]
Fixed
