### ISSUE TITLE
Add support for games that used previous chronological extension

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#4]
Add a configuration item for day/time that will use the column expected in the chronological-mission-posts extension. This will allow users to replace the older extension and have their existing posts display correctly.

Perhaps day/time legacy mode?

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Day Time Legacy Mode should only appear when Day Time Configuration is selected.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
confirmed fixed
