### ISSUE TITLE
All options are showing in 2.7.4

### ISSUE THREAD

**Issue by greenfelt22** [reecesavage/nova-ext-ordered-mission-posts#40]
My current mission has "Nova Default" selected for Timeline Configuration. When I go to write a post, I have options for Mission Day, Date, Stardate, Time, and Timeline. I believe I should only be seeing either Date or Timeline. 

When I select other options in the Mission edit page, I still have all of the above options showing.

**Comment by reecesavage** [comment]
v1.2.0 released with support for Nova 2.7.5+ and PHP 8.
