### ISSUE TITLE
Add Post Numbering functionality

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#5]
Some users prefer to order posts by Post Number rather than the dates. Post Numbering should be an additional option. 

day/time and post numbering, stardate and post numbers, etc.

If post numbering is turned on the Title of the Mission Post will have the Post number prepended to the Title.

Example:
Test Post is the third post made in the mission. Its title would be "Post 3 - Test Post" 
Testing Post is the first post make in the mission. Its title would be "Post 1 - Testing Post"

Post number will be derived from the total number of posts activated in the mission prior to submission.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Post numbering should be configured at the mission level on/off functionality.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Unchecking Post Numbers does not stick after clicking submit.

![image](https://user-images.githubusercontent.com/15860882/106633885-d9220900-6544-11eb-9635-e2e32f5b27e1.png)

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
unchecking post numbering works now.

However, when post numbering is off the sort should return to Date Time/Day Time/Stardate. This is not happening.

![image](https://user-images.githubusercontent.com/15860882/106810015-039dc000-6632-11eb-923a-d0fb3bc95b32.png)

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
confirmed fixed
