### ISSUE TITLE
Add No Date Functionality

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#6]
Allow an option to use the integrated timeline field that Nova uses as default. This would allow users to use post numbering functionality while not using date functionality.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Rename option from "Timeline" to "Nova Default"

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Fixed working
