### ISSUE TITLE
Move configuration from config file the Create and Edit Mission pages

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#7]
Move to the data configuration to the Create and Edit Mission Pages. This will allow the users to select functionality for a given mission and allow them to change their configurations should they want to.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
configuration should be set at the mission level not post level. Please move this functionality to the add mission and edit mission pages. index.php/manage/missions/add and index.php/manage/missions/edit/1

The database column should be the missions table.

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
fixed working
