### ISSUE TITLE
Create an admin page for the extension.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#8]
The Admin page will allow the admins to change the labels for the extension, verify the SQL columns expected are valid in the database, and create any column not found. This will be useful for future versions that might have additional columns.

**Comment by reecesavage** [comment]
Admin Page should provide a button to check the configuration for the extension. This would check for the presence of the required SQL columns and the email function in write.php. There should also be a button to create missing columns or attempt to add the email function to write.php. The goal of this is to make adding the extension user friendly without the need to update files or databases manually.

**Comment by reecesavage** [comment]
![2021-02-06 12_45_34-USS Test __ Configuration](https://user-images.githubusercontent.com/15860882/107127119-98462f00-6879-11eb-968f-37872bddf76e.png)

Add - "Ordered Mission Posts Settings" Title at the top of the page

1. Label Configuration
2. Timeline Configuration - Label
3. Post Numbering - Label
4. Default Mission Date - Label
5. Default Stardate - Label
6. Emulate Chronological Mission Posts - Label
7. Mission Post Day - Label
8. Mission Post Date - Label
9. Mission Post Stardate - Label
10. Mission Post Time - Label
11. Concat - Label (Mission Day 2 **at** 2300)
12. Suffix - Label (Mission Day 2 at 2300 **Hours**)

**Comment by reecesavage** [comment]
![2021-02-08 14_25_38-Window](https://user-images.githubusercontent.com/15860882/107278548-8ef4c800-6a1b-11eb-9117-e914f2acc043.png)
![2021-02-08 14_36_05-Window](https://user-images.githubusercontent.com/15860882/107278565-92884f00-6a1b-11eb-966d-f3ca9ea440ca.png)

1. Configuration Check
2. All expected columns found in the database.
3. Email Configuration Missing or Updated - This is expected if it is the first time you have used this Extension or an update has produced a change. Click the button below to modify your application/controlers/write.php file or check the README file for manual instructions.
4. Update Controller Configuration
5. Database Columns Missing - This is expected if it is the first time you have used this Extension or an update has produced a change. Click the Create Column button below for each missing column or check the README file for manual instructions.
6. No changes. Looks Good.
7. Create Column
8. Email Configuration located, and up to date.

Add a section for chronological_mission_posts.
1. Check to see if post_chronological_mission_post_time and post_chronological_mission_post_day exist in the database.
2. True - chronological_mission_posts database columns detected. You may enable Legacy Mode for existing Missions.
3. False - chronological_mission_posts database columns not detected. You may not enable Legacy Mode for existing Missions.
4. If true allow users to turn on legacy mode support for existing missions.
5. Store the currently created mission ids in a new sql column.

**Comment by reecesavage** [comment]
Add a check to make sure the function in write.php is the one expected. That way if we make a change to the function in a future version the admin panel will detect a mismatch.

**Comment by pawanmall157** [comment]
Last point is pending other points are done

**Comment by reecesavage** [comment]
![2021-02-10 16_53_02-USS Test __ Add Mission](https://user-images.githubusercontent.com/15860882/107583523-a3be9080-6bc0-11eb-8416-9fd83eb5029a.png)
1. Is there a way to have the Ordered Mission Posts admin page appear under a section called Extensions? We will have other extensions that might have admin pages so it would need to check if another extension has already created the Extensions section.

**Comment by pawanmall157** [comment]
Didn't understand properly .
for now there is no extension section https://novadev.game-hosting.org/index.php

please brief about the point

**Comment by reecesavage** [comment]
Just update the custom.js lines 9 and 10

```
$('.menu_category:contains("Characters")')
    .before('<li><a href="<?php echo site_url("extensions/nova_ext_ordered_mission_posts/Manage/config")?>"><span>Ordered Mission Posts</span></a></li><li class="spacer"></li>');
```

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
the Extension admin page should only be available if the user is a System Administrator.

When I login with a standard user I can see the extension

![image](https://user-images.githubusercontent.com/15860882/107863935-86d2c900-6e1d-11eb-96f1-6042e5a03ad1.png)

Check https://github.com/reecesavage/nova-ext-enhanced-extension-manager/blob/master/includes/System.php to see how that extension creates the menu using the Install function. Then you can remove it from custom.js. 

```
'menu_access_level' => 0, - This setting is equal to Sys Admin
```

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
![2021-02-15 11_34_34-USS Test __ Configuration](https://user-images.githubusercontent.com/15860882/107980673-4b074300-6f86-11eb-84a2-82a75031072c.png)
![2021-02-15 11_41_23-USS Test __ Configuration](https://user-images.githubusercontent.com/15860882/107980685-50fd2400-6f86-11eb-82da-d54e82beb214.png)
1. - Change button test to "Update Labels"
2. - Create Index shows even if the index has been created. If the index exists there should be no button. - "All expected indexes found in the database."
3. Can this automatically check on page load without a button click?
4. When adding columns in the Missions table the column is added but the page returns still listing the column unless you refresh the page again. Perhaps the function is not waiting?
5. The menu only shows when a system admin is logged in as expected. However, the admin page will load if you know the link. Please add an auth check to ensure the user is a system admin before rendering the admin page.
```
Auth::check_access('site/settings');
```

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
confirmed fixed
