### ISSUE TITLE
Add default date for Date/Time function

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#9]
When configuring a mission for Date/Time in Add Mission or Edit Mission allow the user to add a start date. This date will be the default date when a user creates a post using Write Mission Post.

**Comment by reecesavage** [comment]
Date Time functionality should show a Default Mission Date Field
Stardate Functionality should show a Default Stardate Field

**Comment by reecesavage** [comment]
Default Mission Date Field should only show when Date Time Selected
Default Stardate Field should only show when Stardate Selected

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
confirmed fixed
